Writing/Technology Assignment One

Exploring Matrix Multiplication

MATH 254 – Linear Algebra

Timothy Paylor

The table [below] shows the first two test scores for Anna, Bruce, Chris, and David. Use the
table to create a matrix M to represent the data. Input M into a software program or
a graphing utility and use it to answer the following questions.

| Name | Test 1 | Test 2 |
| --- | --- | --- |
| Anna | 84 | 96 |
| Bruce | 56 | 72 |
| Chris | 78 | 83 |
| David | 82 | 91 |

In [110]:
# Defining M as above matrix

import numpy as np

M = np.matrix([[84, 96], 
     [56, 72], 
     [78, 83], 
     [82, 91]])
M

matrix([[84, 96],
        [56, 72],
        [78, 83],
        [82, 91]])

1. Which test was more difficult? Which was easier? Explain.

Based on the scores each student received on the two tests, it is likely that the first test was more difficult since all four students received a lower grade compared to the grades they received on the second test.

2. How would you rank the performances of the four students?

The ranking of the students is consistent across both tests with Anna receiving the highest scores, followed by David then Chris then Bruce.

3. Describe the meanings of the matrix products:

M * [[1], [0]] and M * [[0], [1]]

In [109]:
# For M*[[1], [0]]

m = np.matrix([[1, 0]])
print (np.multiply(M,m))

[[84  0]
 [56  0]
 [78  0]
 [82  0]]


M * [[1], [0]] gives us the Test 1 scores and zeroes out the Test 2 scores.

In [108]:
# For M*[[0], [1]]

m = np.matrix([[0, 1]])
print (np.multiply(M,m))

[[ 0 96]
 [ 0 72]
 [ 0 83]
 [ 0 91]]


M[[0], [1]] gives us the Test 2 scores and zeroes out the Test 1 scores.

4. Describe the meanings of the matrix products:

<br>
[[1], [0], [0], [0]] * M and [[0], [0], [1], [0]] * M

In [106]:
# For [[1], [0], [0], [0]]*M

m = np.matrix([[1], [0], [0], [0]])
print (np.multiply(M,m))

[[84 96]
 [ 0  0]
 [ 0  0]
 [ 0  0]]


The operation [[1], [0], [0], [0]] * M gives us only Anna's scores on both Test 1 and Test 2.

In [105]:
# For [[0], [0], [1], [0]]*M

m = np.matrix([[0], [0], [1], [0]])
print (np.multiply(m,M))

[[ 0  0]
 [ 0  0]
 [78 83]
 [ 0  0]]


The operation [[0], [0], [1], [0]] * M gives us only Chris' scores on both Test 1 and Test 2.

5. Describe the meanings of the matrix products:

'M * [[1, 1]]'    and    '(0.5) * M * [[1, 1]]'

In [104]:
# 'M * [[1, 1]]'

m = np.matrix([[1, 1]])
print (np.multiply(M,m))

[[84 96]
 [56 72]
 [78 83]
 [82 91]]


'M * [[1, 1]]' returns the test scores for all four students for both tests.

In [103]:
# '(0.5) * M * [[1, 1]]'

A = np.squeeze(np.asarray(M))
half_A = 0.5 * A

m = np.matrix([[1, 1]])
print (np.multiply(half_A,m))

[[42.  48. ]
 [28.  36. ]
 [39.  41.5]
 [41.  45.5]]


'(0.5) * M * [[1, 1]]' returns values that are half of all of the students' test scores for both tests.